from __future__ import unicode_literals

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

CONFIG_DIR_NAME = ".migradiff"
CONFIG_FILE_NAME = "config.json"
DEFAULT_MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 1024
TEMPERATURE = 0

SYSTEM_PROMPT = (
    "You are a PostgreSQL database migration expert. You will be given"
    " a SQL migration script generated by MigraDiff. Explain what the"
    " migration does in plain English, identify any risks, and suggest"
    " safer alternatives for destructive operations. Be concise and"
    " practical. Format your response with numbered points for each"
    " statement. End with an overall risk assessment: LOW, MEDIUM, or HIGH."
)


def _config_dir():
    return Path.home() / CONFIG_DIR_NAME


def _config_path():
    return _config_dir() / CONFIG_FILE_NAME


def redact_api_key(text):
    return re.sub(r"sk-ant-[a-zA-Z0-9-]+", "sk-ant-***", text)


def resolve_api_key(cli_key=None):
    if cli_key:
        return cli_key
    env_key = os.environ.get("ANTHROPIC_API_KEY")
    if env_key:
        return env_key
    cfg = load_config()
    if cfg and "anthropic_api_key" in cfg:
        return cfg["anthropic_api_key"]
    return None


def load_config():
    path = _config_path()
    if path.exists():
        with open(path, "r") as f:
            return json.load(f)
    return None


def save_config(config):
    d = _config_dir()
    d.mkdir(mode=0o700, parents=True, exist_ok=True)
    path = _config_path()
    with open(path, "w") as f:
        json.dump(config, f, indent=2)
    path.chmod(0o600)


def validate_api_key(key):
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=key)
        client.messages.create(
            model=DEFAULT_MODEL,
            max_tokens=10,
            messages=[{"role": "user", "content": "ping"}],
        )
        return True
    except anthropic.APIStatusError as e:
        msg = str(e)
        if "invalid" in msg.lower() or "401" in msg or "403" in msg:
            raise ValueError("Invalid API key")
        raise
    except ImportError:
        raise


def build_explain_prompt(sql_statements, timestamp, count, has_destructive):
    dest_str = "yes" if has_destructive else "no"
    user_prompt = (
        "Migration script to explain:\n\n"
        "{sql_statements}\n\n"
        "Database context:\n"
        "- Tool: MigraDiff (PostgreSQL schema diff)\n"
        "- Generated at: {timestamp}\n"
        "- Statements: {count}\n"
        "- Destructive operations detected: {dest_str}\n\n"
        "Explain each statement, identify risks, and suggest safer"
        " alternatives where applicable."
    )
    return user_prompt.format(
        sql_statements=sql_statements,
        timestamp=timestamp,
        count=count,
        dest_str=dest_str,
    )


class AIExplainer:
    def __init__(self, api_key):
        self.api_key = api_key

    def explain(self, sql_statements, statements_info):
        import anthropic

        has_destructive = any(s.get("risk") == "destructive" for s in statements_info)
        count = len(statements_info)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        user_prompt = build_explain_prompt(
            sql_statements, timestamp, count, has_destructive
        )

        client = anthropic.Anthropic(api_key=self.api_key)
        try:
            response = client.messages.create(
                model=DEFAULT_MODEL,
                max_tokens=MAX_TOKENS,
                temperature=TEMPERATURE,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = response.content[0].text
            return {
                "text": text,
                "model": DEFAULT_MODEL,
                "generated_at": timestamp,
            }
        except Exception as e:
            msg = redact_api_key(str(e))
            raise RuntimeError("MigraDiff: AI explanation failed: {}".format(msg))


ROLLBACK_SYSTEM_PROMPT = (
    "You are a PostgreSQL database expert specializing in migration"
    " rollbacks. Given a SQL migration script, generate the exact reverse"
    " migration. For each statement, output the SQL that undoes it.\n"
    "\n"
    "Rules:\n"
    "1. Reverse statements in reverse order (last statement rolled back first)\n"
    "2. For DROP TABLE, reconstruct CREATE TABLE from the schema context provided\n"
    "3. For DROP COLUMN, reconstruct ADD COLUMN with exact type from schema context\n"
    "4. For non-reversible operations (TRUNCATE, UPDATE, DELETE), output a"
    " comment explaining why\n"
    "5. Add a WARNING comment for any AI-reconstructed DDL\n"
    "6. Output only valid PostgreSQL SQL and comments\n"
    "7. Never add explanatory prose \u2014 only SQL and SQL comments"
)

ROLLBACK_MAX_TOKENS = 2048


def build_rollback_prompt(migration_sql, source_schema_context=None):
    schema_ctx = (
        source_schema_context
        if source_schema_context
        else "No schema context available."
    )
    user_prompt = (
        "Migration to reverse:\n\n"
        "{migration_sql}\n\n"
        "Source schema context (before migration was applied):\n"
        "{source_schema_context}\n\n"
        "Generate the complete rollback migration in reverse order."
    )
    return user_prompt.format(
        migration_sql=migration_sql,
        source_schema_context=schema_ctx,
    )


def _split_statements(sql_text):
    """Split SQL text into individual statements, preserving comments."""
    if not sql_text or not sql_text.strip():
        return []
    stmts = []
    current = []
    for line in sql_text.split("\n"):
        stripped = line.strip()
        current.append(line)
        if stripped and not stripped.startswith("--") and stripped.endswith(";"):
            stmts.append("\n".join(current).strip())
            current = []
    remainder = "\n".join(current).strip()
    if remainder:
        stmts.append(remainder)
    return stmts


def _is_non_reversible(stmt):
    upper = stmt.strip().upper()
    if upper.startswith("TRUNCATE"):
        return True
    if upper.startswith("UPDATE") and "WHERE" not in upper:
        return True
    if upper.startswith("DELETE") and "WHERE" not in upper:
        return True
    return False


def generate_deterministic_rollback(sql_text):
    """Generate deterministic rollbacks for safe reversible operations.

    Returns a tuple (rollback_sql, needs_ai_statements) where
    needs_ai_statements contains statements that require AI assistance
    (DROP TABLE, DROP COLUMN, etc.).
    """
    if not sql_text or not sql_text.strip():
        return "", []

    stmts = _split_statements(sql_text)
    if not stmts:
        return "", []

    rollback_parts = []
    needs_ai = []

    for stmt in reversed(stmts):
        upper = stmt.strip().upper()

        if _is_non_reversible(stmt):
            rollback_parts.append("-- CANNOT ROLLBACK: {}".format(stmt.strip()))
            rollback_parts.append(
                "-- Data has been permanently deleted. Restore from backup."
            )
            continue

        # ADD CONSTRAINT -> DROP CONSTRAINT (must come before ADD COLUMN)
        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+ADD\s+CONSTRAINT\s+(\S+?)(?:\s|;|$)",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            table = m.group(1).strip()
            constraint = m.group(2).strip().strip('"')
            rollback_parts.append(
                'ALTER TABLE {} DROP CONSTRAINT IF EXISTS "{}";'.format(
                    table, constraint
                )
            )
            continue

        # ADD COLUMN -> DROP COLUMN
        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+ADD\s+(?:COLUMN\s+)?(.+?)(?:\s|;|$)",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            table = m.group(1).strip()
            col_name_match = re.match(r'(?:"([^"]+)"|(\w+))', m.group(2).strip())
            if col_name_match:
                col_name = col_name_match.group(1) or col_name_match.group(2)
                rollback_parts.append(
                    'ALTER TABLE {} DROP COLUMN "{}";'.format(table, col_name)
                )
                continue

        # CREATE INDEX -> DROP INDEX
        m = re.match(
            r"CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(.+?)\s+ON\s+",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            idx_name = m.group(1).strip().strip('"')
            rollback_parts.append('DROP INDEX IF EXISTS "{}";'.format(idx_name))
            continue

        # CREATE TYPE ... AS ENUM -> DROP TYPE
        m = re.match(
            r"CREATE\s+TYPE\s+(.+?)\s+AS\s+ENUM\s*\(",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            type_name = m.group(1).strip().strip('"')
            rollback_parts.append('DROP TYPE IF EXISTS "{}";'.format(type_name))
            continue

        # RENAME COLUMN a TO b -> RENAME COLUMN b TO a
        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+RENAME\s+(?:COLUMN\s+)?([^;\s]+)\s+TO\s+([^;\s]+)",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            table = m.group(1).strip()
            old_name = m.group(2).strip().strip('"')
            new_name = m.group(3).strip().strip('"')
            rollback_parts.append(
                'ALTER TABLE {} RENAME COLUMN "{}" TO "{}";'.format(
                    table, new_name, old_name
                )
            )
            continue

        # CREATE SCHEMA -> DROP SCHEMA
        m = re.match(
            r"CREATE\s+SCHEMA\s+(?:IF\s+NOT\s+EXISTS\s+)?(.+?)(?:\s|;|$)",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            schema_name = m.group(1).strip().strip('"')
            rollback_parts.append('DROP SCHEMA IF EXISTS "{}";'.format(schema_name))
            continue

        # ALTER ... SET DEFAULT -> ALTER ... DROP DEFAULT
        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+ALTER\s+(?:COLUMN\s+)?(\S+)\s+SET\s+DEFAULT",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            table = m.group(1).strip()
            col = m.group(2).strip().strip('"')
            rollback_parts.append(
                'ALTER TABLE {} ALTER COLUMN "{}" DROP DEFAULT;'.format(table, col)
            )
            continue

        # ALTER COLUMN ... TYPE -> needs AI for old type
        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+ALTER\s+(?:COLUMN\s+)?(.+?)\s+TYPE\s+",
            stmt.strip(),
            re.IGNORECASE,
        )
        if m:
            needs_ai.append(stmt)
            continue

        # DROP TABLE / DROP COLUMN / DROP TYPE -> needs AI
        upper_no_comment = re.sub(r"--.*$", "", upper).strip()
        if re.match(r"DROP\s+TABLE", upper_no_comment):
            needs_ai.append(stmt)
            continue
        if re.match(r"ALTER\s+TABLE.*DROP\s+(?:COLUMN\s+)?", upper_no_comment):
            needs_ai.append(stmt)
            continue
        if re.match(r"DROP\s+TYPE", upper_no_comment):
            needs_ai.append(stmt)
            continue

        # Unknown statement — include as-is with a warning
        rollback_parts.append(
            "-- WARNING: Cannot determine rollback for:\n-- {}".format(stmt.strip())
        )

    return "\n\n".join(rollback_parts), needs_ai


def extract_drop_references(sql_text):
    """Extract object names referenced in DROP statements."""
    refs = {"tables": [], "columns": [], "types": []}
    if not sql_text:
        return refs

    for stmt in _split_statements(sql_text):
        upper = stmt.strip().upper()

        m = re.match(
            r"DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?(.+?)(?:\s+CASCADE|\s+RESTRICT)?;?\s*$",
            upper,
        )
        if m:
            refs["tables"].append(m.group(1).strip())

        m = re.match(
            r"ALTER\s+TABLE\s+(.+?)\s+DROP\s+(?:COLUMN\s+)?(.+?)(?:\s+CASCADE|\s+RESTRICT)?;?\s*$",
            upper,
        )
        if m:
            table = m.group(1).strip()
            col = m.group(2).strip()
            refs["columns"].append({"table": table, "column": col})

        m = re.match(
            r"DROP\s+TYPE\s+(?:IF\s+EXISTS\s+)?(.+?);?\s*$",
            upper,
        )
        if m:
            refs["types"].append(m.group(1).strip())

    return refs


def extract_schema_context(conn_url, referenced_objects):
    """Extract DDL for objects referenced in DROP statements from a live database."""
    if not referenced_objects or (
        not referenced_objects["tables"]
        and not referenced_objects["columns"]
        and not referenced_objects["types"]
    ):
        return ""

    context_parts = []

    try:
        from sqlbag import S
    except ImportError:
        return "-- Schema context extraction requires sqlbag"

    try:
        with S(conn_url) as s:
            for table in referenced_objects.get("tables", []):
                schema = "public"
                tbl = table
                if "." in table:
                    schema, tbl = table.split(".", 1)
                tbl = tbl.strip('"')
                schema = schema.strip('"')

                # Get column definitions
                rows = s.execute(
                    """
                    SELECT column_name, data_type, character_maximum_length,
                           is_nullable, column_default
                    FROM information_schema.columns
                    WHERE table_schema = %s AND table_name = %s
                    ORDER BY ordinal_position
                """,
                    (schema, tbl),
                )
                cols = rows.fetchall() if hasattr(rows, "fetchall") else list(rows)

                if cols:
                    col_defs = []
                    for col in cols:
                        col_name, dtype, char_len, nullable, default = col
                        col_sql = '    "{}" {}'.format(col_name, dtype)
                        if char_len:
                            col_sql += "({})".format(char_len)
                        if default:
                            col_sql += " DEFAULT {}".format(default)
                        if nullable == "NO":
                            col_sql += " NOT NULL"
                        col_defs.append(col_sql)

                    table_ddl = "CREATE TABLE {}.{} (\n{}\n);".format(
                        schema, tbl, "\n".join(col_defs)
                    )
                    context_parts.append(
                        "-- Original definition of {}.{}:\n{}".format(
                            schema, tbl, table_ddl
                        )
                    )
                else:
                    context_parts.append(
                        "-- WARNING: Table {}.{} not found in source schema".format(
                            schema, tbl
                        )
                    )

            for col_ref in referenced_objects.get("columns", []):
                table = col_ref["table"]
                col = col_ref["column"]
                schema = "public"
                tbl = table
                if "." in table:
                    schema, tbl = table.split(".", 1)
                tbl = tbl.strip('"')
                col = col.strip('"')
                schema = schema.strip('"')

                rows = s.execute(
                    """
                    SELECT data_type, character_maximum_length,
                           is_nullable, column_default
                    FROM information_schema.columns
                    WHERE table_schema = %s AND table_name = %s AND column_name = %s
                """,
                    (schema, tbl, col),
                )
                info = rows.fetchone() if hasattr(rows, "fetchone") else None
                if info:
                    dtype, char_len, nullable, default = info
                    col_sql = '    "{}" {}'.format(col, dtype)
                    if char_len:
                        col_sql += "({})".format(char_len)
                    if default:
                        col_sql += " DEFAULT {}".format(default)
                    if nullable == "NO":
                        col_sql += " NOT NULL"
                    context_parts.append(
                        "-- Original column {}.{}: \n{}".format(tbl, col, col_sql)
                    )
                else:
                    context_parts.append(
                        "-- WARNING: Column {}.{} not found in source schema".format(
                            tbl, col
                        )
                    )

            for type_name in referenced_objects.get("types", []):
                schema = "public"
                typ = type_name
                if "." in type_name:
                    schema, typ = type_name.split(".", 1)
                typ = typ.strip('"')
                schema = schema.strip('"')

                rows = s.execute(
                    """
                    SELECT e.enumlabel
                    FROM pg_type t
                    JOIN pg_enum e ON t.oid = e.enumtypid
                    JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid
                    WHERE n.nspname = %s AND t.typname = %s
                    ORDER BY e.enumsortorder
                """,
                    (schema, typ),
                )
                enum_labels = [r[0] for r in rows] if hasattr(rows, "__iter__") else []
                if enum_labels:
                    enum_vals = ",\n".join(
                        "    '{}'".format(val) for val in enum_labels
                    )
                    context_parts.append(
                        "-- Original type {}.{}:\nCREATE TYPE {}.{} AS ENUM (\n{}\n);".format(
                            schema, typ, schema, typ, enum_vals
                        )
                    )
                else:
                    context_parts.append(
                        "-- WARNING: Type {}.{} not found in source schema".format(
                            schema, typ
                        )
                    )

    except Exception as e:
        context_parts.append(
            "-- WARNING: Failed to extract schema context: {}".format(e)
        )

    return "\n\n".join(context_parts)


class AIRollback:
    def __init__(self, api_key):
        self.api_key = api_key

    def generate_rollback(self, migration_sql, source_schema_context=None):
        from datetime import datetime, timezone

        import anthropic

        # First pass: deterministic rollback
        deterministic_sql, needs_ai_stmts = generate_deterministic_rollback(
            migration_sql
        )

        # If nothing to roll back
        if not migration_sql or not migration_sql.strip():
            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            return {"text": "", "model": "", "generated_at": timestamp}

        # If all statements handled deterministically, return
        if not needs_ai_stmts and deterministic_sql.strip():
            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            return {
                "text": self._format_rollback_output(
                    migration_sql, deterministic_sql, timestamp
                ),
                "model": "deterministic",
                "generated_at": timestamp,
            }

        # If we have statements needing AI assistance, call Anthropic
        ai_sql_text = "\n".join(needs_ai_stmts) if needs_ai_stmts else migration_sql
        ai_context = source_schema_context or ""

        user_prompt = build_rollback_prompt(ai_sql_text, ai_context)

        client = anthropic.Anthropic(api_key=self.api_key)
        try:
            response = client.messages.create(
                model=DEFAULT_MODEL,
                max_tokens=ROLLBACK_MAX_TOKENS,
                temperature=TEMPERATURE,
                system=ROLLBACK_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            ai_text = response.content[0].text

            # Combine deterministic + AI rollback
            if deterministic_sql.strip() and ai_text.strip():
                combined = deterministic_sql + "\n\n" + ai_text
            elif ai_text.strip():
                combined = ai_text
            else:
                combined = deterministic_sql

            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            return {
                "text": self._format_rollback_output(
                    migration_sql, combined, timestamp
                ),
                "model": DEFAULT_MODEL,
                "generated_at": timestamp,
            }
        except Exception as e:
            msg = redact_api_key(str(e))
            raise RuntimeError("MigraDiff: AI rollback failed: {}".format(msg))

    def _format_rollback_output(self, original_sql, rollback_sql, timestamp):
        parts = []
        parts.append("--- Original Migration ---")
        parts.append(original_sql.strip())
        parts.append("")
        parts.append("--- Rollback Migration ---")
        parts.append("-- Generated by MigraDiff AI")
        parts.append("-- WARNING: Review carefully before applying to production")
        parts.append("-- Rollback generated at: {}".format(timestamp))
        parts.append("")
        if rollback_sql and rollback_sql.strip():
            parts.append(rollback_sql.strip())
        else:
            parts.append("-- Nothing to roll back")
        return "\n".join(parts)


def generate_file_rollback(filepath, api_key=None):
    """Generate rollback for a migration file without schema context."""
    if not os.path.exists(filepath):
        raise ValueError("MigraDiff: File not found: {}".format(filepath))

    with open(filepath, "r") as f:
        sql = f.read()

    if not sql.strip():
        return {"text": "Nothing to roll back", "model": "", "generated_at": ""}

    # Try deterministic first
    deterministic_sql, needs_ai_stmts = generate_deterministic_rollback(sql)

    # If AI-only statements (DROP TABLE/COLUMN) are present, add warnings
    if needs_ai_stmts:
        warning_lines = [
            "-- WARNING: DROP TABLE reversal requires original schema context",
            "-- Run: migra --rollback <connection_string> {}".format(
                os.path.basename(filepath)
            ),
            "-- to generate a complete rollback with schema reconstruction",
        ]
        for stmt in needs_ai_stmts:
            warning_lines.append("-- CANNOT fully reverse: {}".format(stmt.strip()))

        # If nothing deterministically reversible either
        if not deterministic_sql.strip():
            result = "\n".join(warning_lines)
        else:
            result = deterministic_sql + "\n\n" + "\n".join(warning_lines)

        from datetime import datetime, timezone

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        return {
            "text": result,
            "model": "",
            "generated_at": timestamp,
        }

    if not deterministic_sql.strip():
        return {"text": "Nothing to roll back", "model": "", "generated_at": ""}

    from datetime import datetime, timezone

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "text": deterministic_sql,
        "model": "deterministic",
        "generated_at": timestamp,
    }


ADVISE_SYSTEM_PROMPT = (
    "You are a PostgreSQL performance expert specializing in schema"
    " migration risk analysis. For each SQL statement provided, analyze:\n"
    "1. Whether it causes table locks and for how long\n"
    "2. Whether it rewrites table data\n"
    "3. The estimated impact based on table size context provided\n"
    "4. A safer zero-downtime alternative where one exists\n"
    "\n"
    "Format each statement analysis as:\n"
    "Statement N: <sql>\n"
    "Risk: HIGH/MEDIUM/LOW\n"
    "Issue: <specific problem>\n"
    "Estimated impact: <what happens at scale>\n"
    "Safer alternative: <zero-downtime SQL if applicable>\n"
    "\n"
    "End with an overall risk summary.\n"
    "Be specific and practical. Output only the analysis, no preamble."
)

ADVISE_MAX_TOKENS = 2048


def classify_statement_risk(sql):
    """Deterministic pre-classification of a SQL statement's risk level.

    Returns a dict with keys: risk (HIGH/MEDIUM/LOW), issue (str),
    and confidence (float 0-1).
    """
    upper = sql.strip().upper()

    # HIGH risk patterns
    if re.match(r"ALTER\s+TABLE.*ADD\s+(?:COLUMN\s+)?.+\s+DEFAULT\s+", upper):
        return {
            "risk": "HIGH",
            "issue": "ADD COLUMN with DEFAULT may rewrite entire table on PG < 11, "
            "and can still cause table rewrite depending on data type and storage",
            "confidence": 0.9,
        }
    if re.match(r"ALTER\s+TABLE.*ALTER\s+(?:COLUMN\s+)?.+?\s+TYPE\s+", upper):
        return {
            "risk": "HIGH",
            "issue": "ALTER COLUMN TYPE rewrites the entire table and holds an "
            "ACCESS EXCLUSIVE lock",
            "confidence": 0.95,
        }
    if re.match(r"DROP\s+TABLE", upper):
        return {
            "risk": "HIGH",
            "issue": "Irreversible data loss. All rows permanently deleted",
            "confidence": 1.0,
        }
    if re.match(r"ALTER\s+TABLE.*DROP\s+(?:COLUMN\s+)?", upper):
        return {
            "risk": "HIGH",
            "issue": "Irreversible data loss. Column data permanently deleted",
            "confidence": 1.0,
        }
    if re.match(r"TRUNCATE", upper):
        return {
            "risk": "HIGH",
            "issue": "Irreversible data loss. All rows permanently deleted",
            "confidence": 1.0,
        }
    m = re.match(r"CREATE\s+(?:UNIQUE\s+)?INDEX(?:\s+CONCURRENTLY)?\s+", upper)
    if m and "CONCURRENTLY" not in upper.split("INDEX", 1)[1][:20]:
        return {
            "risk": "HIGH",
            "issue": "CREATE INDEX without CONCURRENTLY locks the table "
            "against writes for the entire build",
            "confidence": 0.9,
        }
    # ALTER TABLE ... ADD CONSTRAINT ... NOT VALID
    if re.search(r"ALTER\s+TABLE.*ADD\s+CONSTRAINT.*NOT\s+VALID", upper):
        return {
            "risk": "MEDIUM",
            "issue": "NOT VALID avoids initial table scan but VALIDATE CONSTRAINT "
            "still requires a full scan",
            "confidence": 0.8,
        }
    # ALTER TABLE ... VALIDATE CONSTRAINT
    if re.search(r"ALTER\s+TABLE.*VALIDATE\s+CONSTRAINT", upper):
        return {
            "risk": "MEDIUM",
            "issue": "VALIDATE CONSTRAINT performs a full table scan "
            "which may be slow on large tables",
            "confidence": 0.8,
        }

    # MEDIUM risk patterns
    if re.match(r"ALTER\s+TABLE.*RENAME\s+(?:COLUMN\s+|TO\s)", upper):
        return {
            "risk": "MEDIUM",
            "issue": "Application code may reference the old name",
            "confidence": 0.7,
        }
    if re.match(r"CREATE\s+(?:UNIQUE\s+)?INDEX\s+CONCURRENTLY\s+", upper):
        return {
            "risk": "MEDIUM",
            "issue": "CONCURRENTLY avoids table lock but cannot run "
            "inside a transaction block",
            "confidence": 0.8,
        }
    if re.match(r"ALTER\s+TABLE.*ADD\s+FOREIGN\s+KEY", upper):
        return {
            "risk": "MEDIUM",
            "issue": "Scans both referencing and referenced tables to validate",
            "confidence": 0.7,
        }
    if (
        re.match(r"ALTER\s+TABLE.*ADD\s+(?:COLUMN\s+)?", upper)
        and "DEFAULT" not in upper
    ):
        return {
            "risk": "LOW",
            "issue": "Schema change without DEFAULT is safe — no table rewrite",
            "confidence": 0.9,
        }

    # LOW risk patterns
    if re.match(r"CREATE\s+SEQUENCE", upper):
        return {"risk": "LOW", "issue": "Safe operation", "confidence": 0.95}
    if re.search(r"ADD\s+VALUE\s+IF\s+NOT\s+EXISTS", upper):
        return {"risk": "LOW", "issue": "Safe enum extension", "confidence": 0.95}
    if re.match(r"ALTER\s+TABLE.*ADD\s+CONSTRAINT.*CHECK\s+NOT\s+VALID", upper):
        return {
            "risk": "LOW",
            "issue": "CHECK NOT VALID avoids table scan",
            "confidence": 0.9,
        }
    if re.match(r"COMMENT\s+ON", upper):
        return {
            "risk": "LOW",
            "issue": "Metadata only, no data impact",
            "confidence": 0.95,
        }
    if re.match(r"CREATE\s+SCHEMA", upper):
        return {"risk": "LOW", "issue": "Safe schema creation", "confidence": 0.95}
    if re.match(r"(?:GRANT|REVOKE)\s+", upper):
        return {"risk": "LOW", "issue": "Permission change only", "confidence": 0.95}

    return {
        "risk": "LOW",
        "issue": "No known performance risk pattern",
        "confidence": 0.5,
    }


def build_advise_prompt(numbered_sql_statements, table_stats=None):
    table_stats_text = (
        table_stats
        if table_stats
        else "Table size statistics unavailable (no live connection). "
        "Risk estimates are conservative — actual impact may vary."
    )
    user_prompt = (
        "Migration statements to analyze:\n\n"
        "{numbered_sql_statements}\n\n"
        "Table size context (from source schema statistics):\n"
        "{table_stats}\n\n"
        "PostgreSQL version context: analyze for PostgreSQL 14+ behavior.\n"
        "\n"
        "Analyze each statement for locking risk, table rewrites, and "
        "data loss. Suggest safer zero-downtime alternatives where applicable."
    )
    return user_prompt.format(
        numbered_sql_statements=numbered_sql_statements,
        table_stats=table_stats_text,
    )


def extract_table_stats(conn_url, table_names):
    """Fetch row counts for referenced tables from the source database."""
    if not conn_url or not table_names:
        return ""
    try:
        from sqlbag import S
    except ImportError:
        return ""

    stats_lines = []
    try:
        with S(conn_url) as s:
            for tbl in table_names:
                schema = "public"
                table = tbl
                if "." in tbl:
                    schema, table = tbl.split(".", 1)
                table = table.strip('"')
                schema = schema.strip('"')
                rows = s.execute(
                    """
                    SELECT n_live_tup
                    FROM pg_stat_user_tables
                    WHERE schemaname = %s AND relname = %s
                """,
                    (schema, table),
                )
                row = rows.fetchone() if hasattr(rows, "fetchone") else None
                if row and row[0] is not None:
                    stats_lines.append("- {}: ~{} rows".format(tbl, row[0]))
                else:
                    stats_lines.append("- {}: no statistics available".format(tbl))
    except Exception:
        stats_lines.append("Could not fetch table statistics from source database.")

    if not stats_lines:
        return ""
    return "\n".join(stats_lines)


class AIAdvisor:
    def __init__(self, api_key):
        self.api_key = api_key

    def advise(self, sql_statements, statements_info, table_stats=None):
        import anthropic

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        if not sql_statements or not sql_statements.strip():
            return {
                "text": "No statements to analyze.",
                "model": "",
                "generated_at": timestamp,
                "overall_risk": "LOW",
                "statement_details": [],
            }

        # Number statements for the prompt
        stmts = _split_statements(sql_statements)
        numbered = []
        for i, stmt in enumerate(stmts, 1):
            numbered.append("Statement {}: {}".format(i, stmt))
        numbered_sql = "\n".join(numbered)

        user_prompt = build_advise_prompt(numbered_sql, table_stats)

        client = anthropic.Anthropic(api_key=self.api_key)
        try:
            response = client.messages.create(
                model=DEFAULT_MODEL,
                max_tokens=ADVISE_MAX_TOKENS,
                temperature=TEMPERATURE,
                system=ADVISE_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = response.content[0].text

            # Determine overall risk from text
            overall_risk = "LOW"
            if "HIGH RISK" in text.upper() or "overall risk: HIGH" in text.lower():
                overall_risk = "HIGH"
            elif (
                "MEDIUM RISK" in text.upper() or "overall risk: MEDIUM" in text.lower()
            ):
                overall_risk = "MEDIUM"

            return {
                "text": text,
                "model": DEFAULT_MODEL,
                "generated_at": timestamp,
                "overall_risk": overall_risk,
                "statement_details": [classify_statement_risk(s) for s in stmts],
            }
        except Exception as e:
            msg = redact_api_key(str(e))
            raise RuntimeError("MigraDiff: AI advisory failed: {}".format(msg))


def _numbered_sql_statements(sql_text):
    """Return a numbered list of SQL statements for prompt inclusion."""
    stmts = _split_statements(sql_text)
    numbered = []
    for i, stmt in enumerate(stmts, 1):
        numbered.append("Statement {}: {}".format(i, stmt))
    return "\n".join(numbered)


def generate_file_advisory(filepath, api_key=None):
    """Generate advisory for a migration file."""
    if not os.path.exists(filepath):
        raise ValueError("MigraDiff: File not found: {}".format(filepath))

    with open(filepath, "r") as f:
        sql = f.read()

    if not sql.strip():
        return {
            "text": "No statements to analyze.",
            "model": "",
            "generated_at": "",
            "overall_risk": "LOW",
            "statement_details": [],
        }

    if not api_key:
        return {
            "text": "MigraDiff: --advise requires an Anthropic API key.",
            "model": "",
            "generated_at": "",
            "overall_risk": "",
            "statement_details": [],
        }

    advisor = AIAdvisor(api_key)
    return advisor.advise(sql, [])


GENERATE_SYSTEM_PROMPT = (
    "You are a PostgreSQL migration expert. Generate a SQL migration"
    " script based on the user's description and their actual schema"
    " context.\n"
    "Rules:\n"
    "1. Output only valid PostgreSQL DDL \u2014 no prose, no markdown\n"
    "2. Use exact table and column names from the schema context\n"
    "3. Use appropriate PostgreSQL types (text not varchar, timestamptz"
    " not timestamp, serial or identity for auto-increment)\n"
    "4. Add IF NOT EXISTS where appropriate to make migrations idempotent\n"
    "5. Add CONCURRENTLY to CREATE INDEX statements\n"
    "6. Never DROP anything unless explicitly requested\n"
    "7. Never modify existing columns unless explicitly requested\n"
    "8. Start each statement on a new line\n"
    "9. End each statement with a semicolon\n"
    "10. Add a SQL comment before each logical group of statements"
)

GENERATE_MAX_TOKENS = 2048

HARD_REFUSE_PATTERNS = [
    r"\bdrop\s+all\b",
    r"\bdelete\s+all\b",
    r"\btruncate\s+all\b",
    r"\bdrop\s+everything\b",
    r"\bwipe\b",
]

SOFT_WARN_PATTERNS = [
    r"\bdrop\b",
    r"\bdelete\b",
    r"\btruncate\b",
    r"\bremove\s+table\b",
    r"\bremove\s+column\b",
]


def check_safety_rules(description):
    """Check description against safety rules.

    Returns a dict: {"action": "refuse"|"warn"|"allow", "reason": str}
    """
    lower = description.lower()
    for pat in HARD_REFUSE_PATTERNS:
        if re.search(pat, lower):
            matched = re.search(pat, lower).group()
            return {
                "action": "refuse",
                "reason": 'Description contained: "{}"'.format(matched),
            }
    for pat in SOFT_WARN_PATTERNS:
        if re.search(pat, lower):
            matched = re.search(pat, lower).group()
            return {
                "action": "warn",
                "reason": 'Description contained: "{}"'.format(matched),
            }
    return {"action": "allow", "reason": ""}


def extract_relevant_schema(conn_url, description):
    """Extract relevant table DDL for a description against a live database.

    Returns a string with CREATE TABLE-style definitions for matched tables.
    """
    if not conn_url or not description:
        return ""

    # Find potential table names in the description
    words = re.findall(r"[a-zA-Z_]\w*", description.lower())
    candidates = set()
    stop_words = {
        "table",
        "column",
        "add",
        "remove",
        "all",
        "with",
        "that",
        "have",
        "from",
        "each",
        "every",
        "and",
        "the",
        "for",
        "not",
        "new",
        "null",
        "default",
    }
    for w in words:
        if len(w) > 1 and w not in stop_words:
            # Also include singular/plural variants
            candidates.add(w)
            if w.endswith("s"):
                candidates.add(w[:-1])
            elif not w.endswith("s"):
                candidates.add(w + "s")

    try:
        from sqlbag import S
    except ImportError:
        return ""

    context_parts = []
    found_tables = []

    try:
        with S(conn_url) as s:
            # Find matching tables
            for candidate in list(candidates)[:10]:
                rows = s.execute(
                    """
                    SELECT table_schema, table_name
                    FROM information_schema.tables
                    WHERE (table_name = %s OR table_name LIKE %s)
                    AND table_type = 'BASE TABLE'
                    AND table_schema NOT IN ('pg_catalog', 'information_schema')
                    ORDER BY table_name
                    LIMIT 1
                """,
                    (candidate, "%{}%".format(candidate)),
                )
                matches = list(rows) if hasattr(rows, "__iter__") else rows.fetchall()
                for schema, tbl in matches:
                    entry = "{}: {}.{}".format(len(found_tables) + 1, schema, tbl)
                    if entry not in found_tables:
                        found_tables.append(entry)

                        # Get columns
                        col_rows = s.execute(
                            """
                            SELECT column_name, data_type,
                                   character_maximum_length,
                                   is_nullable, column_default
                            FROM information_schema.columns
                            WHERE table_schema = %s AND table_name = %s
                            ORDER BY ordinal_position
                        """,
                            (schema, tbl),
                        )
                        cols = (
                            list(col_rows)
                            if hasattr(col_rows, "__iter__")
                            else col_rows.fetchall()
                        )
                        if cols:
                            col_defs = []
                            for col in cols:
                                col_name, dtype, char_len, nullable, default = col
                                col_sql = "  {} {}".format(col_name, dtype)
                                if char_len:
                                    col_sql += "({})".format(char_len)
                                if default:
                                    col_sql += " DEFAULT {}".format(default)
                                if nullable == "NO":
                                    col_sql += " NOT NULL"
                                col_defs.append(col_sql)

                            table_ddl = "CREATE TABLE {}.{} (\n{}\n);".format(
                                schema, tbl, "\n".join(col_defs)
                            )
                            context_parts.append(
                                "-- Table {}.{}:\n{}".format(schema, tbl, table_ddl)
                            )

                        if len(found_tables) >= 5:
                            break
                if len(found_tables) >= 5:
                    break

            # Also check for "all tables with column X" pattern
            col_pattern = re.search(
                r"all\s+tables?\s+(?:that\s+)?have?\s+a\s+(\w+)\s+column",
                description.lower(),
            )
            if col_pattern:
                col_name = col_pattern.group(1)
                col_rows = s.execute(
                    """
                    SELECT table_schema, table_name
                    FROM information_schema.columns
                    WHERE column_name = %s
                    AND table_schema NOT IN ('pg_catalog', 'information_schema')
                    GROUP BY table_schema, table_name
                    ORDER BY table_name
                    LIMIT 5
                """,
                    (col_name,),
                )
                matches = (
                    list(col_rows)
                    if hasattr(col_rows, "__iter__")
                    else col_rows.fetchall()
                )
                for schema, tbl in matches:
                    entry = "{}: {}.{}".format(len(found_tables) + 1, schema, tbl)
                    if entry not in found_tables and len(found_tables) < 5:
                        found_tables.append(entry)
                        col_rows2 = s.execute(
                            """
                            SELECT column_name, data_type,
                                   character_maximum_length,
                                   is_nullable, column_default
                            FROM information_schema.columns
                            WHERE table_schema = %s AND table_name = %s
                            ORDER BY ordinal_position
                        """,
                            (schema, tbl),
                        )
                        cols2 = (
                            list(col_rows2)
                            if hasattr(col_rows2, "__iter__")
                            else col_rows2.fetchall()
                        )
                        col_defs = []
                        for col in cols2:
                            cn, dt, cl, nl, df = col
                            cs = "  {} {}".format(cn, dt)
                            if cl:
                                cs += "({})".format(cl)
                            if df:
                                cs += " DEFAULT {}".format(df)
                            if nl == "NO":
                                cs += " NOT NULL"
                            col_defs.append(cs)
                        table_ddl2 = "CREATE TABLE {}.{} (\n{}\n);".format(
                            schema, tbl, "\n".join(col_defs)
                        )
                        context_parts.append(
                            "-- Table {}.{}:\n{}".format(schema, tbl, table_ddl2)
                        )

    except Exception:
        return ""

    if not context_parts:
        return ""

    return "\n\n".join(context_parts)


def build_generate_prompt(description, schema_context):
    schema_text = (
        schema_context
        if schema_context
        else "No schema context available. Use real PostgreSQL types and"
        " conventional naming."
    )
    user_prompt = (
        "Generate a PostgreSQL migration for:\n"
        '"{description}"\n\n'
        "Current schema context:\n"
        "{schema_context}\n\n"
        "Generate only the SQL statements needed. No explanations."
    )
    return user_prompt.format(
        description=description,
        schema_context=schema_text,
    )


def parse_schema_file_for_tables(filepath):
    """Parse a pg_dump -s file for CREATE TABLE statements."""
    if not os.path.exists(filepath):
        return ""
    try:
        with open(filepath, "r") as f:
            content = f.read()
    except Exception:
        return ""

    # Extract CREATE TABLE statements
    tables = re.findall(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(.+?)\s*\((.+?)\)\s*;",
        content,
        re.IGNORECASE | re.DOTALL,
    )
    if not tables:
        return ""

    # Return up to 10 most relevant table definitions
    parts = []
    for name, body in tables[:10]:
        cleaned = re.sub(r"\s+", " ", body.strip())
        parts.append("CREATE TABLE {} ({});".format(name.strip(), cleaned))
    return "\n\n".join(parts)


class AIGenerator:
    def __init__(self, api_key):
        self.api_key = api_key

    def generate(self, description, schema_context=None):
        import anthropic

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        if not description or not description.strip():
            return {
                "text": "MigraDiff: No description provided for generation.",
                "model": "",
                "generated_at": timestamp,
                "schema_context_used": [],
                "is_destructive": None,
            }

        # Safety check
        safety = check_safety_rules(description)
        if safety["action"] == "refuse":
            return {
                "text": (
                    "MigraDiff: Refusing to generate bulk destructive migration.\n"
                    "{}\n"
                    "If intentional, write the SQL manually and use --advise"
                    " to review.".format(safety["reason"])
                ),
                "model": "",
                "generated_at": timestamp,
                "schema_context_used": [],
                "is_destructive": None,
            }

        is_destructive = safety["action"] == "warn"

        # Build schema context
        ctx_tables = []
        if schema_context:
            for line in schema_context.split("\n"):
                m = re.match(r"-- Table (.+?):", line)
                if m:
                    ctx_tables.append(m.group(1))

        # Generate via AI
        user_prompt = build_generate_prompt(description, schema_context)

        client = anthropic.Anthropic(api_key=self.api_key)
        try:
            response = client.messages.create(
                model=DEFAULT_MODEL,
                max_tokens=GENERATE_MAX_TOKENS,
                temperature=TEMPERATURE,
                system=GENERATE_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            generated_sql = response.content[0].text.strip()

            # Build output with header
            lines = []
            lines.append("--- Generated Migration ---")
            lines.append("-- Generated by MigraDiff AI")
            lines.append("-- Description: {}".format(description))
            if ctx_tables:
                lines.append("-- Schema context: {}".format(", ".join(ctx_tables)))
            if not schema_context:
                lines.append(
                    "-- Warning: No schema context available. Generated SQL"
                    " may need adjustment for your actual schema."
                )
            lines.append("-- Generated at: {}".format(timestamp))
            lines.append("-- WARNING: Review before applying to production")
            if is_destructive:
                lines.append(
                    "-- \u26a0 WARNING: This migration contains destructive operations"
                )
                lines.append("-- Review carefully before applying to production")
                lines.append(
                    "-- Consider: migra --rollback to prepare a reversal first"
                )
            lines.append("")
            lines.append(generated_sql)
            lines.append("")
            lines.append("-- Review this migration with: migra --advise migration.sql")
            lines.append("-- Generate a rollback with: migra --rollback migration.sql")

            return {
                "text": "\n".join(lines),
                "model": DEFAULT_MODEL,
                "generated_at": timestamp,
                "schema_context_used": ctx_tables,
                "is_destructive": is_destructive,
                "generated_sql": generated_sql,
            }
        except Exception as e:
            msg = redact_api_key(str(e))
            raise RuntimeError("MigraDiff: AI generation failed: {}".format(msg))


def setup_ai_interactive(out, err):
    key = None
    try:
        import anthropic
    except ImportError:
        print(
            "MigraDiff: --setup-ai requires the AI extras.",
            file=err,
        )
        print("Install with: pip install migradiff[ai]", file=err)
        return 1

    print("MigraDiff AI Setup", file=out)
    print("==================", file=out)

    import getpass

    raw_key = getpass.getpass("Enter your Anthropic API key (input hidden): ")
    key = raw_key.strip()

    print("Validating key...", file=out)

    try:
        validate_api_key(key)
    except ValueError as e:
        print("{}".format(e), file=err)
        print(
            "Please check your key at https://console.anthropic.com",
            file=err,
        )
        return 1
    except anthropic.APIStatusError as e:
        msg = redact_api_key(str(e))
        print("Key validation failed: {}".format(msg), file=err)
        return 1
    except Exception as e:
        msg = redact_api_key(str(e))
        print("Key validation failed: {}".format(msg), file=err)
        return 1

    existing = load_config() or {}
    existing["anthropic_api_key"] = key
    existing.setdefault("ai_model", DEFAULT_MODEL)
    existing.setdefault("explain_verbosity", "standard")

    try:
        save_config(existing)
    except Exception as e:
        print("Failed to save config: {}".format(e), file=err)
        return 1

    print("Key validated successfully.", file=out)
    from pathlib import Path

    config_path = Path.home() / CONFIG_DIR_NAME / CONFIG_FILE_NAME
    print(
        "Saved to {} (chmod 600)".format(config_path),
        file=out,
    )
    print(file=out)
    print("You can now use --explain with any diff command.", file=out)
    print(
        "Run: migra --explain postgres://db_a postgres://db_b",
        file=out,
    )
    return 0
